//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCliente.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IContratoServidor")]
    public interface IContratoServidor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/EnviaStringProServidor", ReplyAction="http://tempuri.org/IContratoServidor/EnviaStringProServidorResponse")]
        bool EnviaStringProServidor(string pMensagemEnviada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/EnviaStringProServidor", ReplyAction="http://tempuri.org/IContratoServidor/EnviaStringProServidorResponse")]
        System.Threading.Tasks.Task<bool> EnviaStringProServidorAsync(string pMensagemEnviada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/PegaStringDoServidor", ReplyAction="http://tempuri.org/IContratoServidor/PegaStringDoServidorResponse")]
        string PegaStringDoServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/PegaStringDoServidor", ReplyAction="http://tempuri.org/IContratoServidor/PegaStringDoServidorResponse")]
        System.Threading.Tasks.Task<string> PegaStringDoServidorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContratoServidorChannel : ServidorCliente.ServiceReference.IContratoServidor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContratoServidorClient : System.ServiceModel.ClientBase<ServidorCliente.ServiceReference.IContratoServidor>, ServidorCliente.ServiceReference.IContratoServidor {
        
        public ContratoServidorClient() {
        }
        
        public ContratoServidorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContratoServidorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServidorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServidorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnviaStringProServidor(string pMensagemEnviada) {
            return base.Channel.EnviaStringProServidor(pMensagemEnviada);
        }
        
        public System.Threading.Tasks.Task<bool> EnviaStringProServidorAsync(string pMensagemEnviada) {
            return base.Channel.EnviaStringProServidorAsync(pMensagemEnviada);
        }
        
        public string PegaStringDoServidor() {
            return base.Channel.PegaStringDoServidor();
        }
        
        public System.Threading.Tasks.Task<string> PegaStringDoServidorAsync() {
            return base.Channel.PegaStringDoServidorAsync();
        }
    }
}
